### ISSUE TITLE
Feature Request: Pull stats info each time your profile is loaded.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#10]
From the little testing I did, it seems like it only pulls the xp/stats from runemetrics the first time the account is loaded. After that, the xp changes based on the different quests/tasks you perform. Even though you are completely various things in doing those tasks that results in xp (Agility shortcuts, random impling, combat etc.) So if you're are following the path to a T, there will be little deviation here and there. But I could see over time this getting larger and larger and could potentially change the path depending on if you've gained levels etc. What I have been doing is manually checking my xp each time I load it up for the day. I usually have to change 2-3 skills which isn't that big of a deal. But if it were possible to pull data each time it loads, that would be a huge time saver in the longer run.

**Comment by RenegadeLucien** [comment]
Done, will be part of 0.7.3b.
