### ISSUE TITLE
Loading indication

### ISSUE THREAD

**Issue by Californ1a** [RenegadeLucien/project-tenacity#13]
From the `How to use` section of the readme:

>It is important to note that if this is your first time using Project Tenacity, the tool must gather Grand Exchange data on all of the items in its item database. This takes approximately 5-7 minutes. Also, every time a profile is created or loaded, the tool will calculate the optimal path for the profile, which will take up to a minute depending on player progress.

While this loading is going on, the program just appears as if it's unresponsive (and even reports as not responding in task manager). It would be much better to have some kind of loading indication instead of locking up the whole program during this.

**Comment by RenegadeLucien** [comment]
On my checklist already. Haven't prioritized it yet because I've been working out bugs in the functionality, but it will definitely happen before release.

**Comment by Californ1a** [comment]
>On my checklist already.

It might be nice to transfer that checklist into individual issues and [tag them with milestones](https://github.com/RenegadeLucien/project-tenacity/milestones) so everyone else who wants to keep up can see what all is left for 1.0.

**Comment by RenegadeLucien** [comment]
Progress bar is done, will be included in v0.9.0b.
