### ISSUE TITLE
Re-calc takes excessive amounts of time

### ISSUE THREAD

**Issue by RenegadeLucien** [RenegadeLucien/project-tenacity#17]
From #15. Re-calcs are reported as taking up to 12 minutes, where the maximum should be 2.

**Comment by Californ1a** [comment]
> \-Is it really taking 12 minutes to complete a single achievement? I've never seen it take more than 2 locally. Only way it should take 12 minutes is if you're deleting the gedata file on every achievement, which is not necessary and I doubt is what's going on here.

Yes, I timed it from hitting the complete achievement/recalc button up until it wasn't marked as "not responding" anymore. From a brand new profile, I sorted the achievements by name/alphabetical, selected `Perfectly Balanced IV` (closed the dialog box), and hit the button+started timer.

**Comment by RenegadeLucien** [comment]
So, I just did the exact steps you listed: create new profile, sort by name, select "Perfectly Balanced IV", recalc, and...it just threw an error message and refused to even perform the re-calc at all.

I'm pretty sure that's a completely separate issue, though. When you created your profile, what was the name you gave it (if any?)

**Comment by RenegadeLucien** [comment]
So I did determine that high-level accounts take a lot longer to recalculate than low-level accounts because they spend a lot more time in the combat simulator (which is about 90% of the total runtime.)

Still haven't found a root cause or fix though. Will keep looking

**Comment by Californ1a** [comment]
>When you created your profile, what was the name you gave it (if any?)

Californ1a, save data from after following the steps I described above is attached: [Californ1a.zip](https://github.com/RenegadeLucien/project-tenacity/files/3205621/Californ1a.zip)

>So I did determine that high-level accounts take a lot longer to recalculate than low-level accounts

Makes sense since there's a lot more stuff to look through for them. Improving performance and cutting down the loading times will significantly help with not only actual usage, but also in testing. It might be beneficial to have some toggles for what data to get when first creating a profile. Stuff like item prices probably isn't needed for a majority of achievements, and could probably be downloaded individually as-needed when marking each achievement or adding an item to the bank tab.

>they spend a lot more time in the combat simulator (which is about 90% of the total runtime.)

Is this necessary to be run on every recalc? I don't believe many achievements would affect the combat calculations. It might be beneficial to piece-out different parts of the recalc, and have the specific achievements determine which parts of the recalc are actually required to be run.

**Comment by RenegadeLucien** [comment]
> Improving performance and cutting down the loading times will significantly help with not only actual usage, but also in testing. 

Trust me, the load times have been the single biggest pain point I've had in this whole project. I've tried lots of different ways to cut them down, but nothing's worked so far. The main culprit is the combat simulator, and usually my attempts to reduce load time involve either steamlining the calculations itself or minimizing the number of required calls to it, but nothing's worked yet.

> Stuff like item prices probably isn't needed for a majority of achievements, and could probably be downloaded individually as-needed when marking each achievement or adding an item to the bank tab.

The issue with that is, every single item in the item database is required to calculate the effective time cost of at least _some_ achievement or action. Yes, in general usage of Project Tenacity you probably wouldn't care about the price of a raw cod...until you try to get the time cost for Cold War, which requires a raw cod.

> Is this necessary to be run on every recalc? I don't believe many achievements would affect the combat calculations. It might be beneficial to piece-out different parts of the recalc, and have the specific achievements determine which parts of the recalc are actually required to be run.

In theory that might be possible, but just about everything (excluding the empty achievements like lodestones) will tie back to the combat simulator in some way. This is because the combat simulator is used to determine minimal gear/stat requirements for things like quests and bosses, and it does this by incrementally upgrading a player's gear and/or stats until it reaches a point where the combat is winnable, then uses that as the "requirements" for the combat. (This is also why the combat simulator takes so long to run, because it often has to upgrade a player's gear and throw it back in the simulator dozens, if not hundreds, of times before it finally reaches a winning outcome.) So anything that might change how long it takes to gain a skill level or piece of gear (which is essentially every skill level, bank addition/removal, or gear addition/removal) will affect the minimal requirements for combat encounters, and thus require recalculation via the simulator.

**Comment by RenegadeLucien** [comment]
Update: I did find a root cause. Turns out there was a bug in the combat simulator--it is supposed to stop and return a result (kills per hour) when it reaches 6000 ticks (one hour) but it was waiting to finish the current enemy before it stopped. For high-level accounts, especially they are loaded with bottom-tier weapons, this would lead to "stalemate" situations where neither player nor monster could do any amount of damage to the other, and the simulated combat would drag on for absurd amounts of time, often hundreds of thousands of ticks.

I added a fix for this--with this fix, the recalc time for a high-level account drops from 10-12 minutes to 45-50 seconds (on my computer.) Fix will be included in v0.8.4b release on Friday.

Closing this issue, as the bug was discovered and fixed. Will open a T60 issue for reducing the load times further, as discussed in previous comments
