### ISSUE TITLE
Put the save file into a better format

### ISSUE THREAD

**Issue by RenegadeLucien** [RenegadeLucien/project-tenacity#20]
From #15. Currently the save file is virtually unworkable outside of Project Tenacity itself, and is also very easy to break. Using JSON or XML for the save file would be a much better experience.

**Comment by RenegadeLucien** [comment]
Done (via JSON). Will be included in v0.8.4b. Note that this will break any existing save files.

**Comment by Californ1a** [comment]
The file extension is still .ptp rather than .json even though the data inside is in json format.

**Comment by RenegadeLucien** [comment]
This was intentional. I gave the save files a unique identifier (PTP = Project Tenacity Player) so that if by chance the user put Project Tenacity into a location that already had a file with the same name as their RSN (e.g. Californ1a.json) Project Tenacity wouldn't overwrite it on save.

I know this is ludicrously unlikely, but it happening just once would cause a huge stink that I would not want to deal with. If you want a JSON file, you can copy the data into a new file and save it as JSON.
