### ISSUE TITLE
Some achievements won't let you complete them

### ISSUE THREAD

**Issue by beckytaylor88** [RenegadeLucien/project-tenacity#30]
Some achievements won't let you complete them.  It seems to be random, but these are the ones I have found so far:
- Ivan is flailing
- Arc II, IV, V, VI, VII, VIII, IX and X achievements
- Treasure seeker VI
- Diving for clues
- Perky like a prawn
I've been trying to do this the same way as for the others, but on clicking the button, nothing happens.  I've restarted and retried - and those same achievements still don't work.

**Comment by RenegadeLucien** [comment]
Issue here is that if the optimal path for completing a task includes performing an action that has an untradeable input (e.g. vyre corpses for cremation in Ivan is Flailing), the task completion workflow will try to find it in the items database, which includes only tradeable items, which causes a failure.

Issue is fixed and the fix will be included as part of v0.8.6b on Friday. In the meantime, you can work around this by manually opening your player data profile file and adding the desired achievement(s) to your "Qualities" section.
