### ISSUE TITLE
Issue with running on MacOS 10.14.5

### ISSUE THREAD

**Issue by JeremyVolin** [RenegadeLucien/project-tenacity#36]
I tried running the standalone files and I'd just get an error message to check the terminal. I also tried running it with something like Eclipse but also got error messages. Here's what my terminal looks like when I tried running it from there:
<img width="896" alt="Screen Shot 2019-07-22 at 2 50 25 PM" src="https://user-images.githubusercontent.com/10050982/61657066-10e19c80-ac90-11e9-9dd9-0f7a7d83edf5.png">

**Comment by RenegadeLucien** [comment]
Looks like the same thing as #35. What version of Java are you running?

**Comment by JeremyVolin** [comment]
I have Java 12.0.2

**Comment by RenegadeLucien** [comment]
Current version of Project Tenacity doesn't have the Mac native libraries for JavaFX built in.

Next version coming tomorrow will include a Mac-specific build that contains these libraries.

**Comment by RenegadeLucien** [comment]
Issue should be fixed. Let me know if you encounter this issue again.
