### ISSUE TITLE
Unable to complete Trimmed Completionist Achievment

### ISSUE THREAD

**Issue by LuxAria** [RenegadeLucien/project-tenacity#39]
When attempting to mark this achievement as complete, the client bugs out and nothing happens.

**Comment by RenegadeLucien** [comment]
Not entirely sure of everything that's going on, but it seems like all of the actions for completing this achievement are clashing with each other. I've dealt with this on a smaller scale before, but not on something the size of Trimmed Completionist Cape. Will do my best to deal with it before v1.0.3.

**Comment by RenegadeLucien** [comment]
So I fixed one issue relating to rounding errors (more details can be found in #42), but it looks like it uncovered a second issue that I haven't diagnosed yet. Still pulling for this to be fixed in v1.0.3.

**Comment by RenegadeLucien** [comment]
Alright, so I'm declaring partial victory on this issue.

There were actually several layers of problems that were preventing completing this achievement, including integer overflows, mishandling of armour and weapons, and mismatches between the completion process and the calculation process regarding how to handle item requirements, all of which added up to the calculator underestimating the amount of actions that needed to be completed. But all of those should be dealt with at this point, and the achievement is now completable.

The "partial" part of this is that it now seems to be massively _over_estimating the actions that need to be completed, the result of this being that completing this achievement will fill up your XP and bank with gigantic numbers. If I'm lucky I'll figure this out fast and this won't be in v1.0.3, but more likely a fix on that will have to be delayed to v1.0.4.
