### ISSUE TITLE
Can not re-sort time cost back to way it is shown upon opening

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#4]
When the program is first loaded it loads sorted by time cost, which results in showing the highest absolute value negative number, moving towards 0.0 then finally counting upwards from there on, which makes sense.. If I were to re-sort it by time cost it changes to "lowest to highest" being 0.0 counting up to the max number including the negatives in with the positives.

**Comment by RenegadeLucien** [comment]
This was because the time costs were being represented in the table as strings instead of numbers. Fix is done and will be part of v0.7.1b.
