### ISSUE TITLE
Requirements for Beneath Cursed Tides are incorrect

### ISSUE THREAD

**Issue by loganpihl** [RenegadeLucien/project-tenacity#40]
Requirements in Tenacity state that 30 Crafting is needed (among 30 Attack, Strength, Woodcutting, Mining, Magic, Firemaking), while the wiki states 30 Cooking is needed (plus all the skills in parenthesis) with no mention of crafting.

**Comment by RenegadeLucien** [comment]
Whoops. Fixed, correction will be in v1.0.3. Nice catch!
