### ISSUE TITLE
Add orikalkum equipment

### ISSUE THREAD

**Issue by kittet** [RenegadeLucien/project-tenacity#43]
Currently orikalkum equipment doesn't show up in the equipment tab.

Also, is there a way to check off an achievement but not get the corresponding reward in your bank? i.e. for achievements that were previously completed.

Thanks!

**Comment by RenegadeLucien** [comment]
Orikalkum full helms, platebodies, platelegs, armoured boots, and gauntlets +0 to +3 have been added to the database and will be present in v1.0.4.

Regarding completing an achievement without receiving the rewards: This will not happen if you complete multiple achievements at once, so if you are marking achievements you already completed it is best to do them all at once, or at least several at a time. (If you are marking only one achievement, you can pair it up with an "empty" achievement like a lodestone.)
