### ISSUE TITLE
Possible pathing error with Araxxor achievements

### ISSUE THREAD

**Issue by Sesme3** [RenegadeLucien/project-tenacity#45]
I'm having trouble saving my lists. Whenever i open the java app i am forced to make a new account everytime. im clicking the save button on the app everytime i exit it

**Comment by Sesme3** [comment]
also getting arraxor achievements popping up at the very top of effective time cost

**Comment by RenegadeLucien** [comment]
Do you see any files in your Project Tenacity folder with the ".ptp" extension?

**Comment by Sesme3** [comment]
i ended up deleting and redownloading the java app and it is letting me save now. idk what was wrong but its fixed now

**Comment by RenegadeLucien** [comment]
Alright, cool.

Regarding the issue with Araxxor achievements, can you post your .ptp file, or at least a screenshot of the main character screen and the recommended actions for one of the Araxxor achievements?

**Comment by Sesme3** [comment]
okay so it seems like me redownloading fixed all my problems. I no longer see any arraxor or kalphite king tasks near the top anymore. That last download was bugged or something. sorry to waste your time

**Comment by RenegadeLucien** [comment]
No worries, glad the issues are resolved. It's possible you might have downloaded an older version of Project Tenacity by accident.
