### ISSUE TITLE
Feature request: Ability to un-complete achievements.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#5]
Not sure if this is even possible to undo "Completed achievements" if I were to accidently have one selected when I go to recalc. The only work around I have right now is to Save my profile data everytime I tick off an achievement, so when I do tick one off by accident I can close the window and reload the save that has it unticked.

**Comment by RenegadeLucien** [comment]
This is already possible by removing the achievement in question from the "Qualities" tab of the player table and recalculating. I have added this to the readme file.
