### ISSUE TITLE
River of Blood - Incorrect Number of Tome reads

### ISSUE THREAD

**Issue by proEndreeper** [RenegadeLucien/project-tenacity#54]
In the rewards for [River of Blood](https://runescape.wiki/w/River_of_Blood#Rewards), Project Tenacity lists for me that I can use the Tome of XP 5th edition 5 times to get 75,000 xp, when the book only lets you use it 3 times. Unless there is an after reward I'm missing, I believe that it should only be 3 quantities of 75,000 xp not the 5 it's showing for me.

![image](https://user-images.githubusercontent.com/1905293/72774760-0b2a2c80-3bc9-11ea-8422-8b8562636155.png)

**Comment by RenegadeLucien** [comment]
Nice catch. I think I put 5 rewards because it's called the tome of XP "5th ed"...

Will be fixed in the next version, which I'll put out on Friday. I also need to catch up on the last 5 months of updates, don't I...

**Comment by RenegadeLucien** [comment]
1.0.7 is out, Issue is fixed.
