### ISSUE TITLE
Torva full helm, platebody and platelegs is missing from armour database

### ISSUE THREAD

**Issue by proEndreeper** [RenegadeLucien/project-tenacity#55]
When I tried to add Torva full helm, Torva platebody and Torva platelegs to my armor tab, none of them existed. Upon looking at the code, it doesn't appear anything but the Torva boots and Torva gloves are in the armor database.

**Comment by RenegadeLucien** [comment]
Added. Will be included in v1.0.7.

**Comment by RenegadeLucien** [comment]
1.0.7 is out, Issue is fixed.
