### ISSUE TITLE
Feature Request: Add a spot to add in lamps/stars etc you receive from daily TH keys.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#6]
It would be useful to have somewhere to input that you received a lamp or star or something similiar and it would output what the best skill to use it on would be. I don't think the optimal path should be DEPENDENT on or include TH/MTX in its pathing. But having it calc what the best time cost is for each skill to help you later on down the road during the grinding non-quest portions would be helpful.

**Comment by RenegadeLucien** [comment]
Feature is done and will be included in v0.7.2b.
