### ISSUE TITLE
T99 error code when creating profile with public runemetrics

### ISSUE THREAD

**Issue by ScenicWorld** [RenegadeLucien/project-tenacity#64]
Attempted to create a profile with username ScenicWorld. My runemetrics is public however it comes up with an error message advising to raise as T99 issue due to my profile being public.

**Comment by RenegadeLucien** [comment]
Well aware, this is due to Archaeology. Having an extra skill in the mix broke the RuneMetrics calls. This will be fixed in the next version, hoping to have it out this week.

**Comment by RenegadeLucien** [comment]
Foxed in v1.0.10.
