### ISSUE TITLE
Easier Method of Ticking Off Achievements without Recalcing

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#75]
I think it would be hugely beneficial to this project to be able to easily tick off multiple achievements that are already completed without recalculating. Here's my issue: it's been a while since I've used PT and no longer have a working profile. So I've created a new one and there is a ton of achievements/tasks that have been completed but they're not logged in runemetrics. So I'm going through and marking complete all the achievements I've previously completed, this will automatically add the xp to my character profile. So after I mark complete all the achievements I will have to go back through and manually change all my xp/levels to what they actually are. I feel like during the profile creation process or even just like a tab, where you can go through and checkbox the ones you have completed prior to loading in your profile, and then being able to click save and have all them mark as complete without affecting your characters levels. This will greatly decrease the time it takes to completely set up a brand new profile and use PT on an account that isn't brand new. Also you don't have to wait a few seconds each time you tick off an achievement.

**Comment by RenegadeLucien** [comment]
You already can. Shift-click on multiple achievements at once and then click recalc. If you complete multiple at once it won't update your xp.
