### ISSUE TITLE
T99 Name does not fit into a URL

### ISSUE THREAD

**Issue by Deolord** [RenegadeLucien/project-tenacity#79]
getting error when trying to use valid rs3 name for new profile and after entering it i get an error saying it doesnt fit into a URL for some reason and to raise a t99 issue #

**Comment by GaryLeutheuser** [comment]
Looks like the client is getting blocked by RuneMetrics:

`java.io.IOException: Server returned HTTP response code: 403 for URL: https://apps.runescape.com/runemetrics/profile/profile?user=Brootality`

The endpoints work fine in a browser, though (I'm using chrome specifically).

**Comment by YoruIchka** [comment]
same issue for me, Is there any way to fix it ?

**Comment by RenegadeLucien** [comment]
Well...crap.

I know RuneMetrics had a major outage a couple weeks ago. But I don't know if this is related. If Jagex locked down the RuneMetrics endpoints I might be SOL unless I know the new requirements to querying them (if I need to send a header or something.)

**Comment by RenegadeLucien** [comment]
I did find a fix. Other things are breaking now, but this will be addressed in a patch ASAP.

**Comment by Vadevious** [comment]
You absolute legend, hooray!

**Comment by YoruIchka** [comment]
I don't know what is your irl name 
but I will call you a legend my dude

**Comment by YoruIchka** [comment]
Also do you have a approximate date of when your gonna be able to release the patch ?

**Comment by RenegadeLucien** [comment]
Fixed in v1.1.0a.
