### ISSUE TITLE
Feature Request: Back button in the starting screens.

### ISSUE THREAD

**Issue by CoincidalRS** [RenegadeLucien/project-tenacity#8]
This is seriously NOT that big of a deal. And dependent on the effort, I completed understand if you dont want to add it, as its purely a Quality of Life feature. But a back button the Create New profile screen would be helpful in case you accidentally select it. The only workaround I found so far is to just reload the program, which isn't that big of a deal at all.  Like I said, if it takes more than 5 minutes then just close this issue and bury it. Just something I thought that may be convenient when it becomes more mainstream. The only real time it would save is the 2-3 minutes it takes to reload the program. (It will never be the full 10min to load GE since to get to that screen you'd have to load it at least once so its a non-issue.)

**Comment by RenegadeLucien** [comment]
Done, will be part of v0.7.3b.
