### ISSUE TITLE
T99 issue Looks like the name doesn't fit into a URL for some reason

### ISSUE THREAD

**Issue by Ty-deo** [RenegadeLucien/project-tenacity#80]
Hey there, attaching a picture with the error. Believe it's something to do with Runemetrics

![image](https://user-images.githubusercontent.com/33262714/148575502-8399c4b1-0a52-4387-8946-b0774278db05.png)

**Comment by RenegadeLucien** [comment]
See https://github.com/RenegadeLucien/project-tenacity/issues/79. For some reason Jagex is blocking queries to RuneMetrics from Project Tenacity. Haven't figured out a workaround yet.
